language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: oGYgP9V5TMq6TndH8DFDvkjfvtBmG827HykfWuOpSbyXVXgoOk+qt+tij+aVqTHBEqRK9D6FPtjgqbNDfmMy22YS15V3yWINtqIbFyeQxEvLxfjbiSyhy0ZEJgBQ6oyvYAzRTD5Td966jflL1HXABWaUbRdJeXdIRBdX1oBYQLTq3l1LscD9bRA3WeIDRBdZiqempMKdlRPeUttFLnFajxDEhIjTCu5lQZxFge6NWCJsXeaJRe407a9sI2ucs+OjaYyFcYJTYJhowpScS86E4Y+f7bHania/OKr6abC1A84bGleH1vg1ydhV6YjaR4inw752uoVqY6kj0Wd9Jx6dojZsVIq03G941e0J+BnZKUhW0Y/sgabzntTnPjyGubdKIJwS7tK17TTsbSTQ7cFlHrmg/2PGtjFRnXL54PdOu8xyeF64rNx4v8ZPMDYADeb6FYoomTX13wxc/vq1EN/ek2zkFFiZnW3n/BPKQCmQFnz4rGvOBk3j8rTixob44sL3C9q9Z17nfRJX5zQ1PwBlniw9EMptWRW+i283oonkpgYwiKm+s2sV1WtM7fZXYlIsjmNFnXD9WsYR66fGkLuKk2evD9ZMNbMwIZo2gbDDXzYXNwMy4lu9QgT/NQtpGFG6zzdswWGY/cVOVn7LGGenXbJziJgxBiXJzii7DHz0190=
  app: trello-testing
  on:
    repo: Btan579/trello-testing
