language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: UNgklRH3o/NJdNbrQP0ZN811AkXmfwrCtai0FJpS0khCDwOYY9rukM8SKTgVfh1C91ALYwIWZYYg+RRXGM8E1OM19sru8kW5/6OZ8c7e2t3/+aahwcE/TogFycvP4drBu5pDWkf2r5tAOVQbFCkfFbW5zs8wf5xDN/7g8Mh+N67IS3kRu4iGt/VXtzl+icr6EY3k3FgccodfJNkCNvna+EBCvJT3zeEoUk1wNTkEYBR2VX/pY6ePQQyBQD4ytChPuKTnI9rxP1qjz0207AE82pzxhbDPd3oAXWKtTsZEbejhscWP5xLPrplJy+8CGBBQY9r98l6rOOIrUesnzVbrt/4ikds0M+y260kXR31vZVH7O8gC7+i/WflCUAPOWEfpSVxtZ7xMgtlVRTNMOqXKcXQVjEeUrOH/QycGCKs/Oaknfo5uIYRl/6MJETgrzXck3NxirTN2soCLdR9p/aOKrfiLUd5BDq4gJwtwHEQ2HLhUW9spX889K9dD6ojtiiX1KgJPUWPixGwYFYihg2Tr5EyRY1+LIZ+qI1iPvaa0BHrYe4hww/MhK2ItUIN+g/AkuYCfqCW4ii1R3lq3mYFiDpbAJx5HVjdImiwqmgf/h0ZWTBYtmLK61s+5ta0IdtnEikaDqB0nhNgSVzHTpg2z3flibFhGfWHCzdI7VUL3yFM=
  app: trello-testing
  on:
    repo: Btan579/trello-testing
